version: 0.5.0
session-length: 3600000
base-path-prefix: /opt/wallet/
bitcoin:
  autolock-time: 1800
  wallet-filepath: 1800
  blockchain-filepath: 1800


modules:
  PinModule:
    max-retry: 5

  AuthorizationServerModule:
    host: 89.89.89.89
    port: 8080
    endpoints:
      set-secret: /authorization/secret/set
      overwritte-secret: /authorization/secret/overwritte
    https: true

  PushButtonModule:
    some: configuration

  ExampleModule:
    example: example
    name: name

