version: 0.5.0
base-path-prefix: /opt/wallet/
autolock-seconds: 1800

bitcoin:
  network: testnet
  user-agent: RaspberryWallet

server:
  keystore-name: RaspberryWallet.keystore
  keystore-password: raspberrywallet
  key-alias: ssl

modules:
  PinModule:
    max-retry: 5

  AuthorizationServerModule:
    host: 127.0.0.1
    port: 8080
    endpoints:
      set-secret: /authorization/secret/set
      overwrite: /authorization/secret/overwritte
    https: true

  PushButtonModule:
    some: configuration

  ExampleModule:
    example: example
    name: name

