version: 0.5.0
base-path-prefix: /opt/wallet/
autolock-seconds: 300

bitcoin:
  network: testnet
  user-agent: RaspberryWallet

server:
  keystore-name: RaspberryWallet.keystore
  keystore-password: raspberrywallet
  key-alias: ssl
  port: 80
  secure-port: 433

modules:
  PinModule:
    max-retry: 5

  AuthorizationServerModule:
    host: https://127.0.0.1
    port: 8443
    accept-untrusted-certs: true
    endpoints:
      set-secret: /authorization/secret/set
      overwrite: /authorization/secret/overwrite

  PushButtonModule:
    some: configuration

  ExampleModule:
    example: example
    name: name

